### ISSUE TITLE
Supplementary materials 

### ISSUE THREAD

**Issue by pierrepeterlongo** [ratschlab/metagraph#211]
Dear metagraph authors. 

Thanks a lot for this impressive work. I'm looking for the supp mat pointed out in the manuscript. I was not able to find them, and the pointer https://github.com/ratschlab/metagraph_paper_resources does not exists.

Best, 
Pierre

**Comment by akahles** [comment]
Dear @pierrepeterlongo,

Thank you very much for reporting this issue. Please also accept our apologies for the late reply. We were pushing in the last days to further complete the material and improve the preprint, already incorporating the first feedback.

The above repository should now be publicly accessible and will be further filled with content over the next days. We are also in the process of uploading a new version of the preprint (with extended methods and supplemental material) to BioRxiv, which should become available in the next days as well.

Thanks again for the patience.

Best,

Andre
