### ISSUE TITLE
How to use as a local server?

### ISSUE THREAD

**Issue by phiweger** [ratschlab/metagraph#258]
Thank you for this great tool.

I was wondering, do you have any advice/ instructions on how to serve sequence queries on a local server, analogous to what you provide through the API on the metagraph website?

Thx!

**Comment by phiweger** [comment]
Ah, I guess this it the way to do it: 

https://github.com/ratschlab/metagraph/tree/b4a05e820c91913147ba5407a702a5c78bd30756/metagraph/scripts/cloud

In the README the examples use a script called `main.py`, which does not exist in the "cloud" directory. Is this a placeholder or where can I find it?

Thx again.

**Comment by karasikov** [comment]
Hi Adrian!

> Ah, I guess this it the way to do it:
> 
> https://github.com/ratschlab/metagraph/tree/b4a05e820c91913147ba5407a702a5c78bd30756/metagraph/scripts/cloud

No, this is a custom server for managing custom jobs and processing raw samples in the cloud (before constructing an index).

If you have already got an index constructed, queries can be served in a server regime with
`./metagraph server_query -i <graph> -a <annotation> --port <port> -p <n_threads>`.
Then, use python API to connect to this locally running server on port `<port>` to do queries.

Hope this helps.

**Comment by phiweger** [comment]
so `./metagraph server_query` will basically load the index in memory and expose port `<port>` right?

how do you serve it on GCP if I may ask, ie as a single server instance?

the article mentions the ability to distribute the index across instances -- how would one do this?

thanks for your help!

**Comment by karasikov** [comment]
One can start multiple metagraph server processes on a single or multiple machines, so then the API connects to all of them and distributes the queries.

**Comment by phiweger** [comment]
I will try that, thanks @karasikov for your quick help!
