### ISSUE TITLE
metagraph build fails on protein sequences

### ISSUE THREAD

**Issue by phiweger** [ratschlab/metagraph#261]
I try to use

```
./metagraph build -k 12 -o ix $DATA
```

on a multiline fasta (protein sequence with line breaks).

Here's an example `less $DATA`

```
>t3db_target|P29803 Pyruvate dehydrogenase E1 component subunit alpha, testis-specific form, mitochondrial
MLAAFISRVLRRVAQKSARRVLVASRNSSNDATFEIKKCDLYLLEEGPPVTTVLTRAEGL
KYYRMMLTVRRMELKADQLYKQKFIRGFCHLCDGQEACCVGLEAGINPSDHVITSYRAHG
VCYTRGLSVRSILAELTGRRGGCAKGKGGSMHMYTKNFYGGNGIVGAQGPLGAGIALACK
YKGNDEICLTLYGDGAANQGQIAEAFNMAALWKLPCVFICENNLYGMGTSTERAAASPDY
YKRGNFIPGLKVDGMDVLCVREATKFAANYCRSGKGPILMELQTYRYHGHSMSDPGVSYR
TREEIQEVRSKRDPIIILQDRMVNSKLATVEELKEIGAEVRKEIDDAAQFATTDPEPHLE
ELGHHIYSSDSSFEVRGANPWIKFKSVS
>t3db_target|P68871 Hemoglobin subunit beta
MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPK
VKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFG
KEFTPPVQAAYQKVVAGVANALAHKYH
```

Metagraph errs out with

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

Is this a bug?

**Comment by akahles** [comment]
Hi @phiweger,

The alphabet to be used is set at compile time. For proteins, you would need to supply `-DCMAKE_DBG_ALPHABET=Protein` to cmake. This is currently a bit hidden in the README. We will improve the documentation on this.

Best,

Andre

**Comment by phiweger** [comment]
I did compile with this flag.

**Comment by phiweger** [comment]
More specifically, Incompiled vanilla, DNA worked, deleted the build dir, recompiled with the flag for proteins, then the error.

**Comment by karasikov** [comment]
This could be caused by some parameters that are not adapted for the amino acids alphabet.

Try to supply build with this flag `./metagraph build --index-ranges 4 ...`

We'll merge the fixes for alternative alphabets to the main branch soon.

**Comment by karasikov** [comment]
Stay tuned with #249

**Comment by phiweger** [comment]
works! thx @karasikov
