### ISSUE TITLE
index downloads missing

### ISSUE THREAD

**Issue by marade** [ratschlab/metagraph#274]
Thanks for making this wonderful tool. Perhaps I am missing something obvious here, but I wonder where the indexes are? The paper says "All indexes created from public data comprising in total more than 1 million records are available for download or usage in the cloud." Is this true? If so, where are they located?

**Comment by akahles** [comment]
Dear @marade ,

Thank you very much for reaching out. As the manuscript is still a pre-print, we are still organising all the relevant data. Once everything is in place, you will be able to find links to the indexes on metagraph.ethz.ch.

Thanks and Cheers,

Andre

**Comment by marade** [comment]
Ah, good to know. Looking forward to seeing your work published!

**Comment by akahles** [comment]
Dear @marade ,

We have now added a menu item "Indexes" to the metagraph.ethz.ch webpage, providing downloadable versions of the indexes. We will close this issue for now. Please re-open in case you still experience problems.

Cheers,

Andre
