### ISSUE TITLE
Allow two lists as input to metagraph assemble

### ISSUE THREAD

**Issue by phiweger** [ratschlab/metagraph#291]
When differentially assembling two large groups, the current way of individually specifying each `--label-mask-in` and `--label-mask-out` on the command line can lead to the latter complaining about the input being too long. It would be cool to simply specify two lists or a `json` or some file that lists all the labels for each group.

```
metagraph assemble --label-mask-in in.txt --label-mask-out out.txt ...
```

Thx!

**Comment by hmusta** [comment]
We currently have a pull request where this is going to be incorporated. After some tweaks, it should be merged some time next week.

**Comment by phiweger** [comment]
Is there any update on this issue @hmusta ?

**Comment by hmusta** [comment]
Sorry for the delay, we are still working out some minor issues in the pull request before merging.

Feel free to work in the diff_assembly_canonical branch for the time being.

**Comment by karasikov** [comment]
@phiweger Another way to deal with large numbers of labels for inclusion/exclusion is to build a single column for them in the first place.

That is, build a graph from all sequences, then annotate all those that you would mask as `--label-mask-in` with
```
metagraph annotate --anno-label IN   -o sample_in  file_in_1.fa file_in_2.fa ... file_in_N.fa
```
and similarly for the excluded sequences:
```
metagraph annotate --anno-label OUT   -o sample_out  file_out_1.fa file_out_2.fa ... file_out_M.fa
```

Then run the differential assembly passing both of these aggregated columns:
```
metagraph assemble -a sample_in.column.annodbg \
                   -a sample_out.column.annodbg \
                   --label-mask-in IN \
                   --label-mask-out OUT  ...
```

This doesn't require any json file and is even more computationally efficient, which may be critical if you have a large application.

**Comment by phiweger** [comment]
@karasikov There might be a bug in what you suggest.

I have built 2 annotation files like so:

```bash
metagraph annotate --anno-label bar -i graph.dbg -o graph.bar $DATA_BAR
# same for "foo"
```

But differential assembly fails:

```bash
metagraph assemble \
        -a graph.foo.column.annodbg \
        -a graph.bar.column.annodbg \
        --label-mask-in foo \
        --label-mask-out bar \
        -o /data/diff_assembled 
        /data/graph.dbg

[2021-05-17 07:33:09.573] [error] Mask-out label bar is not found in annotation
```

However, when I run `metagraph stats` on the `bar` annotation I get reasonable output, so I guess the file is not corrupted:

```
=================== ANNOTATION STATS ===================
labels:  1
objects: 31473797
density: 0.598361
representation: column
```

Is it possible that there is some bug in adding more than one annotation file like `metagraph assemble -a ... -a ...`?

**Comment by karasikov** [comment]
Hi Adrian,

It indeed was loading only the first annotation, probably a side-effect of one of the recent changes. Thanks for catching.

I pushed a fix https://github.com/ratschlab/metagraph/commit/2083d711135fa482dece690200027f473c31f9c3 to branch `dev`.

If you want to still use the version from the last release without updating, a workaround would be to merge these two annotations before running assemble. Simply run this command:
```bash
metagraph merge_anno -o foo_bar graph.foo.column.annodbg graph.bar.column.annodbg
```
and pass this new foo_bar to assemble:
```
metagraph assemble \
        -a foo_bar.column.annodbg \
        --label-mask-in foo \
        --label-mask-out bar \
        -o /data/diff_assembled 
        /data/graph.dbg
```

**Comment by phiweger** [comment]
Thanks @karasikov the workaround worked (I'll stick to this version bc/ I use the Docker container you provide), thanks for the blitz response :)

**Comment by phiweger** [comment]
@karasikov do these changes affect the differential assembly fn as well? I want to get all DNA fragments that appear in `foo` but not `bar`. 

```bash
metagraph assemble \
    --unitigs -p 8 \
    -a graph.foo_bar.column.annodbg \
    --label-mask-in foo \
    --label-mask-in-fraction 1 \
    --label-mask-out bar \
    --label-mask-out-fraction 0 \
    -o diff_assembled \
    graph.dbg
```

When I look at the content of the resulting `.fasta` file and search the fragments it returns against the genomes used to build the original graph, I find that they are unique to the individual genomes and not shared across the `foo` group. Am I using the command wrongly? Or is this a bug also?

**Comment by karasikov** [comment]
Hi Adrian,

Your observations are valid.

Building a joint label for all genomes from group `foo` is equivalent to merging all of them with `OR`.
Hence, your command assembles sequences from k-mers that are present in at least one of the genomes from group `foo` and absent in all of the genomes of group `bar`.

If you want the assembled sequences to contain k-mers from all the genomes of `foo`, you need to annotate them separately: foo_1, foo_2, ....

The command will be:
```bash
metagraph assemble \
    --unitigs -p 8 \
    -a graph.foo_bar.column.annodbg \
    --label-mask-in foo_1 \
    --label-mask-in foo_2 \
    ...
    --label-mask-in foo_N \
    --label-mask-in-fraction 1 \
    --label-mask-out bar \
    --label-mask-out-fraction 0 \
    -o diff_assembled \
    graph.dbg
```

**Comment by phiweger** [comment]
ah that makes sense, which brings me back to the first post of this issue :)

**Comment by karasikov** [comment]
@phiweger, Harun has changed the differential assembly flags in #225 quite a bit.
The interface should now be way more flexible.
Check it out and, as usual, feel free to reach out for help, if something is unclear! :)

**Comment by phiweger** [comment]
Thanks and great work, I'll close this then.
