### ISSUE TITLE
Differential assembly does not complain when wrong labels are passed

### ISSUE THREAD

**Issue by phiweger** [ratschlab/metagraph#321]
I accidentally added non-existent labels `--label-mask-in` and `--label-mask-out` to the `metagraph assemble` command (say I annotated label "foo", but then tried to use a label "bar" for differential assembly). It passes, assembling I don't know what (neither does Blast), and does not complain about not finding the labels. I would expect this to throw an error, what do you think?

**Comment by karasikov** [comment]
Hi Adrian,

This was fixed in #314. Currently, it does print an error as you suggest.

Could you please check which commit you're on?

**Comment by phiweger** [comment]
I'm using the Docker container: `docker pull ratschlab/metagraph:0.1.0`

**Comment by karasikov** [comment]
Yes, or switch to the more recent container (must be `ratschlab/metagraph:0.2.0`)
