### ISSUE TITLE
Missing file for annotating the graph with k-mer counts

### ISSUE THREAD

**Issue by Glfrey** [ratschlab/metagraph#356]
Hi,

I'm trying to annotate a graph with k-mer counts via the 'metagraph annotate' option. Given my command is `metagraph annotate -i Seq_1.dbg seq_1.fa --count-kmers -o Seq_1 --anno-filename` the error is `ERROR: Cannot read from file seq_1.fa.fasta.gz`. How do I get this required file? I already counted the k-mers in the 'build' stage and got a file called "Seq_1.dbg.weights" but I don't seem to be able to use this for anything downstream.

Also, if I don't use the `--anno-filename` flag during the annotate process, I also get an error `Error: No annotation to add`.

**Comment by karasikov** [comment]
Hi, you need to transform this "sample graph" with k-mer counts to contigs and annotate with them:

So, just execute this before `metagraph annotate`:
`metagraph transform --to-fasta ... Seq_1.dbg -o seq_1 -p <NUM_THREADS>`
(also pass  `--primary-kmers` to `metagraph transform` if the graph `Seq_1.dbg` was constructed in the canonical mode).

You can find some more examples here https://github.com/ratschlab/counting_dbg/blob/master/scripts.md
These scripts were used to construct a joint index of 2652 RNA-Seq samples with k-mer counts.

Please let me know if this worked.

**Comment by karasikov** [comment]
Excuse me, I made a mistake in my first reply. You need to call `metagraph clean` instead of `metagraph transform`, to fetch the counts along with the contigs. It doesn't actually remove any k-mers unless you pass additional special cutoff parameters, so no worries about that. It just extracts all the contigs with counts for those k-mers. Then you can annotate your final graph using these contigs and it will automatically use their attached counts if you pass `--count-kmers` to `metagraph annotate`.

I updated the reply, it should be good now.

**Comment by Glfrey** [comment]
Thank you so much for your rapid reply, I'll try that out now and get back to you.

**Comment by Glfrey** [comment]
Your commands worked great, thank you, although I do still have to specify `--anno-filename  ` else I receive the error `Error: No annotation to add`. 

I'm now just wondering what I can do with the counts file now I have it? It's not in a readable format, and none of the other programs, such as `metagraph query`, `metagraph transform_anno`, `metagraph assemble` seem to recognize it as they all say ` [error] Unknown annotation format in '200_test.column.annodbg.counts'`. 

Ultimately I'd like to be able to determine k-mer coverage of a contig (e.g. how many times each specific k-mer of the contig appears in the graph) which could tell me, for example, if the contig sequence may be duplicated. Or from an RNA-seq perspective, how many times the sequences appears so I can determine it's expression level. Is is possible to get that information using MetaGraph?

**Comment by karasikov** [comment]
> although I do still have to specify --anno-filename else I receive the error Error: No annotation to add.

Yeah, this is normal. One has to specify what to use a "label" (column name) when annotating the graph. So one of the following flags must always be passed to `metagraph annotate`: `--anno-filename`, `--anno-header`, or `--anno-name <LABEL>`.

> I'm now just wondering what I can do with the counts file now I have it? It's not in a readable format, and none of the other programs, such as metagraph query, metagraph transform_anno, metagraph assemble seem to recognize it as they all say [error] Unknown annotation format in '200_test.column.annodbg.counts'.

`*.annodbg.counts` is an intermediate thing. Once you got the column `*.column.annodbg` and the counts `*.column.annodbg.counts`, you need to convert them to another annotation representation (e.g.,`int_brwt` or a more compressed `row_diff_int_brwt`).

So just run this command:
```bash
metagraph transform_anno --anno-type int_brwt -o 200_test 200_test.column.annodbg
```
This will generate `200_test.int_brwt.annodbg`, which you can then pass to `metagraph query` as an annotation to query counts:
```bash
metagraph query -i graph.dbg -a 200_test.int_brwt.annodbg --count-kmers <CONTIGS>.fasta.gz
```
This command will print the result in a csv format:
```
<query seq id>    <fasta header of the query seq>    <Label (something like 200_test.fastq.gz)>:<total count>
```
where `<total count>` is computed as the sum of the k-mer counts from the query sequence.

This should cover the case you described.

**Comment by karasikov** [comment]
You can also get more information, like compute any count quantiles with flag `--count-quantiles`, e.g.,
```bash
metagraph query -i graph.dbg -a 200_test.int_brwt.annodbg --count-kmers <CONTIGS>.fasta.gz \
    --fast --count-quantiles '0 0.5 1'
```
to print MIN, MEDIAN, and MAX of counts for the k-mers from each contig.

**Comment by Glfrey** [comment]
This is brilliant, thank you. The server I use is down at the moment but I'll certainly play around with the commands and output when it's back online. Thank you for help!
