### ISSUE TITLE
Metagraph fails to build with AppleClang 13

### ISSUE THREAD

**Issue by thomastzhou** [ratschlab/metagraph#359]
**Issue**
Metagraph fails to build on MacOS with AppleClang 13 (Xcode 13) as seen in [this workflow run](https://github.com/ratschlab/metagraph/runs/4365800753). This workflow was run on a branch identical to master, which [has a workflow run that previously passed](https://github.com/ratschlab/metagraph/runs/4223149081) using AppleClang 12.

One possible solution would be to use `macos-11` instead of `macos-latest` in the workflow, and recommend compiling with homebrew's `g++11` on newer versions of MacOS.

**Comment by karasikov** [comment]
I wonder why it fails to compile with Xcode 13
