### ISSUE TITLE
Conda install not successful

### ISSUE THREAD

**Issue by dawnmy** [ratschlab/metagraph#375]
I installed `metagraph` 0.3.3 with conda, and conda did not complain during the installation. However when I start metagraph after installation in the command line, it reports: 
```
36499 illegal hardware instruction (core dumped)  metagraph 
```
The CPU of my server node is: `Intel(R) Xeon(R) CPU E5-2680 v2`, flags in `cpuinfo`:
```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse 
sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl 
xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 
cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand 
lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms 
xsaveopt dtherm ida arat pln pts md_clear flush_l1d
``` 

and the OS is:
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 29 (Twenty Nine)
Release:	29
Codename:	TwentyNine
```

I also tried to download the binary files from the release, both version 0.3.3 and 0.3.2 of `metagraph_DNA` gave the same error as above.

I was wondering what might be the cause of the issue?

**Comment by dawnmy** [comment]
Update:

It worked on another node with: `Intel(R) Xeon(R) CPU E5-2698 v4`. So the cause of the issue is that older version of CPU does not support certain instructions used by metagraph.

**Comment by karasikov** [comment]
It will now pre-compile static binaries without MSSE4.2 instructions as well and upload them on every future release.

Can you try this binary to see if this runs on your machine?

https://github.com/ratschlab/metagraph/suites/5086127291/artifacts/151796696
Run the *_noAVX binary from the archive.

**Comment by dawnmy** [comment]
Thank you for providing the binary without MSSE4.2 instructions. Great that you will upload it on every release. Yes both metagraph_DNA_noAVX and metagraph_DNA worked for me.

**Comment by karasikov** [comment]
Hm... This is interesting. `metagraph_DNA` should be complied with all instructions, so it should be as the one provided by bioconda. Anyway, I'm glad it worked.
