### ISSUE TITLE
Help interpreting k-mer coordinate output

### ISSUE THREAD

**Issue by Glfrey** [ratschlab/metagraph#403]
Hello again,

I'm trying to make sense of the output of a k-mer coordinate search. I'm getting results that look like below:

```
0	TraesCS4A02G403700.1	CDS.faTraesCS4A02G403700.100
1	TraesCS3A02G154800.1	CDS.faTraesCS3A02G154800.100
2	TraesCS3A02G154800.1	CDS.faTraesCS3A02G154800.100:CDS.faTraesCS3D02G162200.100
```

I gather from the below parameter that metagraph uses bins to store k-mer coordinates:

`--coord-binsize [INT]	stepsize for k-mer coordinates in input sequences from the fasta files [1000]`

So am I to gather the "100" I am seeing above means the sequences are all in the 100th bin? This doesn't make sense to m given what I know about the input and I can't seem to make heads nor tales of the results.

**Comment by karasikov** [comment]
Hi Gillian,

That's a method we used in the past but now it's actually obsolete, as you can use the Counting de Bruijn graphs methods with `metagraph annotate --coordinate ...`. See more docs here https://metagraph.ethz.ch/static/docs/quick_start.html#index-k-mer-coordinates

Once an index is constructed, you can query it with `metagraph query --query-coords ...`

Let me know if you need more details.

**Comment by Glfrey** [comment]
Hi @karasikov,

Thank you for your rapid reply! Unfortunately that doesn't seem to an option on the current release:

```
metagraph align --coordinate  -i CDS.dbg -o CDS CDS.fa 
ERROR: Unknown option --coordinate
```

I installed the version I'm using via conda and I did run an update to be sure and the message remains the same.

**Comment by karasikov** [comment]
If you want to query coordinates, simply run `metagraph query --query-coords`.

Alignment is run a bit differently. @hmusta Could you help with this?

**Comment by karasikov** [comment]
This could happen for an outdated version. Where do you pull the release from? If you're using docker, could you please switch to `ghcr` (https://github.com/ratschlab/metagraph/pkgs/container/metagraph)?

**Comment by Glfrey** [comment]
I got the release I was using from anaconda. I did update it but it made no difference so I just reinstalled in a fresh environment and now it seems to be working. Is this what the output should look like?

`15218	TraesCS7D02G291100.1	<CDS.fa>:0-160328441-160328460:0-160331475-160331494:41-160328482-160328504:41-160331516-160331538:0-1558900-1558979:0-1561946-1562025:0-117774432-117774511
15219	TraesCS7D02G291100.1	<CDS.fa>:0-117774532-117774555:0-160328541-160328564:0-160331575-160331598:45-160328586:45-160331620:0-1559000-1559079:0-1562046-1562125:45-117774577-117774611:67-160328608-160328620:67-160331642-160331654
15220	TraesCS7D02G291100.1	<CDS.fa>:0-160328641-160328648:0-160331675-160331682:0-1559100-1559179:0-1562146-1562225:0-117774632-117774711:29-160328670-160328720:29-160331704-160331754`

**Comment by karasikov** [comment]
Yeah, sure!

`15218`  -- query seq id
`TraesCS7D02G291100.1`  -- query seq name
`CDS.fa` -- sample match 1
Then you have k-mer matches delimited with `:` in format `<coord of the first k-mer in query>-<coord of the first k-mer in sample (CDS.fa)>-<coord of the last k-mer in sample>`
`0-160328441-160328460` -- k-mers with coordinates 160328441-160328460 in the indexed sample `CDS.fa` match the respective segment of the query sequence starting from position 0 in the query.

**Comment by Glfrey** [comment]
@karasikov apologies for the delay and thank you so much for your help!

**Comment by hmusta** [comment]
One follow-up question: for your analysis, do you need to perform an alignment (i.e., inexact matching) of your queries against the graph, or is fetching the coordinates from exact k-mer matches sufficient?

If you need to perform an alignment, it can be done using `metagraph align ...`. Given an annotator that encodes k-mer coordinates, you'd have to run `metagraph align -i CDS.dbg -a <ANNOTATOR FILE> --align-chain CDS.fa`. There are a number of other parameters you can set (e.g., seed length, scoring model, etc.), which are described in the help menu `metagraph align --help`.

**Comment by Glfrey** [comment]
Hi

**Comment by Glfrey** [comment]
Hi @hmusta,

I actually need to do both. Will the `metagraph align -i CDS.dbg -a <ANNOTATOR FILE> --align-chain CDS.fa` give the coordinates of where the sequence aligns?

**Comment by hmusta** [comment]
Yes, along with the alignment CIGAR string (the sequence of edits) and some other alignment statistics.

**Comment by Glfrey** [comment]
Brilliant, thank you!

**Comment by hmusta** [comment]
I'm not sure what kinds of measures you have in mind when you say you want to compare the alignments. Could you please elaborate?

**Comment by Glfrey** [comment]
Hi @hmusta sorry for the delay. I've solved this, I essentially just wanted to see the alignment scores for different sequences in my annotations file. I was able to do this by using a joint annotation file as the alignment/query annotation file  and metagraph automatically showed me the alignment scores for both.
