### ISSUE TITLE
Metagraph ignores mem cap and disk swap running out of memory

### ISSUE THREAD

**Issue by enricorox** [ratschlab/metagraph#405]
I am trying to annotate a graph with the following command
`./metagraph annotate -p 4 --mem-cap-gb 8 --disk-swap /tmp -v -i SRR5853087.dbg --coordinates --anno-filename -o SRR5853087 SRR5853087.fa`
where SRR5853087.dbg comes from 
`./metagraph build -p 4 --mem-cap-gb 8 -v -k 31 -o SRR5853087.fa`

It keeps running out of memory and I don't know why since it is supposed to use the disk when the buffer is full.

> Out of memory: Killed process 9242 (metagraph) total-vm:130473448kB, anon-rss:15060836kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:110652kB oom_score_adj:0

Ubuntu 20.04.4
Metagraph 0.3.4
RAM 16GB
system swap file 32GB

**Comment by karasikov** [comment]
Hi Enrico,

The current implementation does not fully support annotation with limited-size buffers when you annotate with coordinates.
Basically, you need to have enough memory to keep that annotation column uncompressed in RAM (roughly 8 bytes per k-mer) when annotating it.
This's only during construction. Once a column is annotated, it's flushed to disk, so you only need to have enough RAM for one.
Then, once all the columns are ready, of course, you can transform them to a more compressed form (e.g., `row_diff_coord` or `row_diff_brwt_coord`).

**Comment by enricorox** [comment]
Thank you so much for the fast response and the valuable advice @karasikov!
In order to circumvent this limitation, can I use a huge Linux swap file?

**Comment by karasikov** [comment]
It writes a bunch of integers to a buffer and sorts them at the end of the construction, so I think it won't be fast if one just uses a swap file for that buffer. In principle, it could be done with some sorting in external memory, but for now, it's not implemented.

Currently, one option without writing any extra code could be to split the input file into smaller ones and annotate them as separate columns. Do you think that could work for you? How big is the input file? If it contains multiple sequences, it could naturally be split to keep fewer sequences in each file (or single sequence per file).

**Comment by karasikov** [comment]
I added the support for disk-swapped construction of columns with coordinates in #406. This will be available in the next version release. You can also try it out earlier if you're compiling from source or you can also use it with [docker](https://github.com/ratschlab/metagraph/pkgs/container/metagraph/) once that PR is merged to the master branch. Your command is good, it will work without any changes.

**Comment by enricorox** [comment]
Sorry for the late reply.
I'm using SRR5853087.sra downloaded from NCBI and converted in FASTA. It's about 7.8GB, I don't know exactly how to annotate the graph separatly, do I need simply to split the file?

Thank you so much for adding disk-swap feature!
I'm compiling from source so I let you know if it's working for me.

**Comment by karasikov** [comment]
I merged this feature to master. It will be supported since version 0.3.5.

**Comment by enricorox** [comment]
This is working great, thanks!
