### ISSUE TITLE
Dealing with reads and a reference genome

### ISSUE THREAD

**Issue by Glfrey** [ratschlab/metagraph#407]
Hello,

I'm trying to build a graph containing reads from a sample and the reference genome to which I want to compare. However, for reads I understand it's best to construct a graph in canonical mode, extract primary k-mers and then build a graph from these. For the reference genome though a non-canonical graph should be constructed (am I right here?). Operating on the assumption my  statements are correct, it's not possible to merge these two different graphs, I tried and got the error:

`[2022-06-11 21:58:44.766] [trace] Metagraph started
[2022-06-11 21:58:45.520] [error] Input graphs are in different modes and thus incompatible for merge`

If I want to perform such an analysis is it acceptable to build a non-canonical graph for the reads and so keep the graphs in the same format?

Thank you for your help as always.

**Comment by karasikov** [comment]
All correct, for reference genomes it's better to construct everything in the `basic` mode (which is also a default).

If you indeed want to represent genomes and reads in a joint graph, the best strategy would probably be to build everything in the `basic` mode but index each read with its reverse-complement (just add flag `-r` when building sample graphs from the read sets).

Are you actually running `metagraph merge`? Keep in mind that it's obsolete and should not be called. If you want to merge two graphs, the way to do it is:
- Step 1) extract contigs from each graph with `metagraph transform --to-fasta ...` (remember that in the `basic` mode you don't need to pass `--primary-kmers`)
- Step 2) build a joint graph from all the contigs and annotate it using the same contigs.

**Comment by karasikov** [comment]
My bad, the correct flag is `--fwd-and-reverse`, not `-r`.

**Comment by Glfrey** [comment]
Hi @karasikov,

Thank you for that. However building with the `-fwd-and-reverse` takes a prohibitive amount of memory for me for my reference and samples. Would an acceptable strategy be to build a graph for each sample and merge them as you described above?

**Comment by karasikov** [comment]
Did you try constructing with disk swap (e.g., `--disk-swap /tmp --mem-cap-gb 10`)?

Do you want to index all reads or you'd like to do some graph cleaning beforehand?

Feel free to describe your setup in more detail so I can make my suggestions more specific.

**Comment by karasikov** [comment]
Sure thing, the cleaning can be done using any available tool. It may not even be necessary, I just wanted to clarify whether the problem in a graph that is too large (i.e., it contains more k-mers than you expected) or if you're indeed ultimately trying to build that large graph but it runs out of memory. Sounds like it's the latter. So, yeah, `--mem-cap-gb` is the thing you need.
It's actually not the strict upper bound but the size of the buffer collecting k-mers (so the name of this flag is a bit confusing, sorry about this). If you want to stay below 500 GB, set it to something around 400-450 GB. In fact, it's always sufficient to set it to something around 80 GB even when you build graphs with a trillion of k-mers. So I'd recommend just setting it to 80 GB.

**Comment by Glfrey** [comment]
Yeah potentially my project is too large, I'm aiming to see how many sample I can cram in to establish an upper limit given my computational constraints. I understand you've done whole SRA taxonomies so I know massive graphs are possible but I don't quite need to construct anything that size. 

Thanks for the recommendation, I'll use that in future constructions. I was able to construct a graph in the end with my samples and reference so I'm thrilled.  If I set to 20-80Gb what should I set my memory limit as when I submit the script? We have a system that I have to request resources so it's a mandatory flag. Would I need only a couple of hundred Gb?

I really appreciate your help here. If you want to chat in anymore detail about the set up and what I'm doing in more detail we could trade e-mails? Metagraph is seriously a game changer for my research!

**Comment by karasikov** [comment]
Of course, I'll be happy to chat! e-mail mikhaika@inf.ethz.ch or any other platform.

> Thanks for the recommendation, I'll use that in future constructions. I was able to construct a graph in the end with my samples and reference so I'm thrilled. If I set to 20-80Gb what should I set my memory limit as when I submit the script? We have a system that I have to request resources so it's a mandatory flag. Would I need only a couple of hundred Gb?

This construction first will need some RAM for the buffer (+ a minor overhead). Then it will release the buffer and will build the final graph at the very end. So you basically need to reserve enough RAM to load the final graph in RAM (which is sometimes very hard to estimate). Though, we know that the final graph takes <1 byte per k-mer in the default `stat` state (typically 4-6 bits), so if you expect it to have, say, 100 bln k-mers, 100 GB RAM will be enough.
So the formula is: `max(<graph size: X GB>, <buffer size: 50 GB + some overhead, depending on the number of threads, say, 5-10 GB>)`.
Once the graph is constructed, you can convert it to the small representation (`metagraph transform --state small ...`) which takes about 3 bits per k-mer.

When you build huge graphs with trillions of k-mers, though, I'd recommend building with flags `metagraph build --inplace --state small ...`. This will build and serialize each internal thing of the graph sequentially, in the smallest state. So 2 bits per k-mer for the X in the formula should be enough (which is 250 GB for a graph with a trillion of k-mers). The only thing about building with `--inplace` is that it doesn't index k-mer ranges (an optimization in the graph that speeds up k-mer queries). So, don't forget to run `metagraph transform --index-ranges 10 -o graph_indexed graph.dbg` on a graph constructed with `--inplace`.

**Comment by Glfrey** [comment]
Hi @karasikov, thank you for that information. I'm having an issue building a graph that merged contains from multiple graphs. I keep getting an error message that metagraph can't open the temp files:

`[2022-06-27 05:38:22.445] [trace] Splitting k-mers from chunk 
/tmp/temp_kmers_jmH4zA/chunk_m13 into 16 chunks...
[2022-06-27 05:38:22.445] [trace] Splitting k-mers from chunk 
/tmp/temp_kmers_jmH4zA/chunk_m5 into 16 chunks...
[2022-06-27 05:38:22.716] [error] Unable to open 
/tmp/temp_kmers_jmH4zA/chunk_m17_split_11 for writing
[2022-06-27 05:38:22.716] [trace] Cleaning up temporary directory 
tmp/temp_kmers_jmH4zA"
[2022-06-27 05:38:22.717] [error] Unable to open 
/tmp/temp_kmers_jmH4zA/chunk_m7_split_11 for writing
[2022-06-27 05:38:22.717] [error] Unable to open 
/tmp/temp_kmers_jmH4zA/chunk_m3_split_11 for writing
[2022-06-27 05:38:22.717] [error] Unable to open 
/tmp/temp_kmers_jmH4zA/chunk_m14_split_11 for writing`

I've ran it twice and got the same error.

**Comment by Glfrey** [comment]
Hi @karasikov, good shout it very well could be. My limit is 262144 and I don't think I'll have the permissions to increase that number but I'll contact my sys admin, or as you say, reduce thread number. Thank you for your seemingly never-ending solutions to the problems I find!

**Comment by karasikov** [comment]
Hi Gil, the new release (https://github.com/ratschlab/metagraph/releases/tag/v0.3.6) contains a bunch of reliability improvements, including this thing. So it should now automatically detect the maximum allowed number of open files and should work fine regardless of the limits set in the system. Please let me know if you notice the same issues again.
This new version will be available on Bioconda very soon, the update has already been merged.
