### ISSUE TITLE
Python API RuntimeError

### ISSUE THREAD

**Issue by mr-eyes** [ratschlab/metagraph#409]
Hi,

I attempt to use the Python API but it threw a `RuntimeError`.

I used the same [example](https://github.com/ratschlab/metagraph/blob/master/metagraph/docs/source/api.rst#example-of-search-in-metasub) in the docs.

Tested on Python `3.10.5`.

Error:
```bash
RuntimeError: Error while calling the server API. 400: <!doctype html>
<html lang=en>
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

Thanks,

**Comment by karasikov** [comment]
Hi, there seems to be an issue with request forwarding.

Please use `api.metasub.ch` instead of `dnaloc.ethz.ch` for now. This should solve the problem.

```
from metagraph.client import GraphClient

metasub = GraphClient('api.metasub.ch', 80, api_path='/api/metasub19')

lbls = metasub.column_labels()
```

**Comment by mr-eyes** [comment]
Thanks for the quick response! It worked now.

I have one more question. Where can I find the list of `api/$databases` like the `metasub19` and `uhgg`?

**Comment by karasikov** [comment]
It's the last column on this page https://metagraph.ethz.ch/graphs

**Comment by mr-eyes** [comment]
Many thanks!
