### ISSUE TITLE
Metagraph for pangenome analysis

### ISSUE THREAD

**Issue by Glfrey** [ratschlab/metagraph#410]
This isn't an issue per se, but rather a theoretical question. Could metagraph be used for a non-read based pangenome analysis? II understand it would function beautifully for a read-based analysis, but if an abundance of beautifully assembled genomes should present themselves for pan-genome analysis (wouldn't that be nice), could metagraph lend itself to such an application without needing to resort back to reads? Originally I thought so until I remembered that it operates using k-mers instead of the usual non-overlapping chunks I see used for pan genomes. Would it be possible to overcome this?

I see metagraph being mentioned in quite a few recent pan genome papers so I think I'm probably not the only one wondering this.

**Comment by Glfrey** [comment]
Brilliant, thank you. Metagraph is truly a game changing tool and I'm very grateful for the responsiveness to my (never-ending) queries. I'll close this as it's not really an issue but is it worth posting this information in the GitHub readme so others can see?

**Comment by karasikov** [comment]
Thanks for your suggestion. I added a line about this to the readme.
