### ISSUE TITLE
Use a file of file

### ISSUE THREAD

**Issue by pierrepeterlongo** [ratschlab/metagraph#412]
Hi there. 
Thanks for this fantastic work.

Is there a way to give a file of files to metagraph? 
Imagine this tree:

```
.
|-- A
|   |-- a1.fq.gz
|   `-- a2.fq.gz
|-- B
|   |-- b1.fq.gz
|   |-- b2.fq.gz
|   `-- b3.fq.gz
|-- C
|   |-- c1.fq.gz
|   `-- c2.fq.gz
```

The behavior I’m looking for would be

```
cat A/* > a.fq.gz
cat B/* > b.fq.gz
cat C/* > c.fq.gz
metagraph ... a.fq.gz b.fq.gz c.fq.gz ...
```

But the explicit concatenation is too expensive.
In kmtricks for instance we could use a file of files like this:

```
name_A: a1.fq.gz  a2.fq.gz
name_B: b1.fq.gz  b2.fq.gz  b3.fq.gz
name_C: c1.fq.gz  c2.fq.gz
```

And run kmtricks on this fof. Each line is considered a unique set of reads (for counting, filtering erroneous kmers, labeling, ...).
Is there a way to do this with metagraph?

**Comment by karasikov** [comment]
Hi Pierre,

As we've already briefly discussed this on e-mail, I'm just going to summarize the answer here.

The graph itself can be constructed from multiple files -- simply pipe the list of all files to `metagraph build`:
```
find A/* B/* C/* -name "*.fq.gz" | metagraph build --disk-swap /tmp --mem-cap-gb 10 -o graph ...
```
or cat from a list of all the files: `cat list_all.txt | metagraph build ...`.

Once a graph is constructed, it needs to be annotated, which can be done in different ways.
One option would be to build each annotation column in its own process:
```
metagraph annotate -i graph.dbg -o name_A --anno-label name_A a1.fq.gz a2.fq.gz
metagraph annotate -i graph.dbg -o name_B --anno-label name_B b1.fq.gz b2.fq.gz b3.fq.gz
...
```
... also see other flags for `metagraph annotate`, like `--coordinate`.

Next, these columns can be transformed to something more efficiently queryable, like `row_diff_sparse` or `row_diff_brwt_coord`.

However, in the annotation step, each command of `metagraph annotate` will start a process that will have to load the graph, which can add a big overhead for large graphs.
So it indeed might be easier to prepare the inputs by merging those files and annotate all of them at once in one run with
```
cat list_all.txt | metagraph annotate -i graph.dbg -o annotation --anno-filename --separately --threads-each 9 -p 4
```
(notice the difference between `--anno-filename` here and `--anno-label ...` in the commands above).
This will load the graph once and will annotate all the columns in parallel (4 columns at a time, using 9 threads for each, so 36 threads in total. Here we annotate only 4 columns at a time to reduce the RAM usage, but still use multiple threads for each to annotate faster and use all the available threads).
