### ISSUE TITLE
New method of annotating and querying coordinates?

### ISSUE THREAD

**Issue by Glfrey** [ratschlab/metagraph#438]
Hello again!

On an older version of metagraph on my Mac, I'm able to annotate meta graph using `metagraph annotate --coordinates` and then querying this structure using `metagraph query --query-coords`. However, a newer version I just installed on a ubuntu server returns:

```
(metagraph):~/metagraph/k11$ metagraph annotate --coordinates

ERROR: Unknown option --coordinates
```

```
(metagraph) :~/metagraph/k11$ metagraph query --query-coords 

ERROR: Unknown option --query-coords
```

I've found `metagraph coordinate` which I don't remember seeing when I was working with Metagraph previously, so is this the new method of coordinate annotation? If I do that then I query the output coordinate file, I can't really make sense of the output. 

I'd really appreciate your help once again.

**Comment by karasikov** [comment]
Hi,

`--coordinates` is the correct command to use with the latest version, your commands should work.

(`metagraph coordinate ...` is an obsolete thing, hence hidden. It will also likely be removed in the future.)

Can you double-check the version of metagraph, what does `metagraph --version` return?

**Comment by Glfrey** [comment]
Hi @karasikov,

Rather unhelpfully, `metagraph --version` returns nothing about the version:

```
(metagraph):~ metagraph --version
Usage: metagraph <command> [command specific options]

Available commands:
	build		construct a graph object from input sequence
			files in fast[a|q] formats into a given graph

	clean		clean an existing graph and extract sequences from it
			in fast[a|q] formats

	extend		extend an existing graph with new sequences from
			files in fast[a|q] formats

	merge		integrate a given set of graph structures
			and output a new graph structure

	concatenate	combine the results of the external merge or
			construction and output the resulting graph structure

	compare		check whether two given graphs are identical

	align		align sequences provided in fast[a|q] files to graph

	stats		print graph statistics for given graph(s)

	annotate	given a graph and a fast[a|q] file, annotate
			the respective kmers

	coordinate	given a graph and a fast[a|q] file, annotate
			kmers with their respective coordinates in genomes

	merge_anno	merge annotation columns

	transform	given a graph, transform it to other formats

	transform_anno	change representation of the graph annotation

	assemble	given a graph, extract sequences from it

	relax_brwt	optimize the tree structure in brwt annotator

	query		annotate sequences from fast[a|q] files

	server_query	annotate received sequences and send annotations back
```

**Comment by karasikov** [comment]
Good. This means it's too old. The solution will be to update to a newer version. The latest is 0.3.6.

**Comment by Glfrey** [comment]
I can't seem to do this as the same Conda error as on my other issue keeps cropping up.

**Comment by karasikov** [comment]
Since this issue is due to using an old version, I'm closing it.
Let's focus on installing the most recent version.
