### ISSUE TITLE
Alignment output

### ISSUE THREAD

**Issue by Glfrey** [ratschlab/metagraph#460]
Hello again, long time no posting!

I'm revisiting some of my older work and I just wanted to clarify the output of `metagraph align`. What are the different column headers? I've put the ones I can figure out below

1. Query name
2. Query sequence
3. Strand
4. Reference sequence
5. ?
6. ?
7. CIGAR string-like alignment summary
8. ?
9. Ref name matches 

Could you help me fill in the bits I'm missing?

Thank you as always!

**Comment by karasikov** [comment]
Hi Gillian! Could you paste the exact command and a line of the output, please?

**Comment by hmusta** [comment]
@Glfrey The one's you've guess so far are right, there's the whole list:

1. Query name
2. Query sequence
3. Strand
4. Reference sequence
5. **Alignment score**
6. **Number of exact matches**
7. CIGAR string-like alignment summary
8. **Number of nucleotides trimmed from the prefix of the reference sequence**
9. Ref name matches

Column 8 only really applies if you have a short alignment that's less than the graph k.
