### ISSUE TITLE
Transform does not create "kmer_counts.gz"-file

### ISSUE THREAD

**Issue by MitraDarja** [ratschlab/metagraph#463]
Hi,

I am trying to use metagraph with the count option and I run in the following warning message when I annotate: `No k-mer counts found at 'trans_100.kmer_counts.gz'. Every input k-mer will have count 1.`, which is not want I want.

There is no `trans_100.kmer_counts.gz`, therefore the message is correct, but I don't understand why transform does not create the file.

I do the following things:
```
metagraph build --parallel 4 -k 21 --count-kmers --count-width 32 --outfile-base graph_100 ../100.fa
metagraph transform -p 4 --to-fasta -o trans_100 graph_100.dbg
metagraph annotate -i metagraph_single/first.dbg --anno-filename --count-kmers --count-width 32 -o 100_anno trans_100.fasta.gz
```

Any help would be greatly appreciated!

**Comment by hmusta** [comment]
If you run your second step in the `clean` regime instead of `transform` with the same flags you're using it should produce the counts file.

**Comment by MitraDarja** [comment]
Hey, thanks for the quick answer! That worked. I am then not supposed to use the transform for the counting option or do I use at some later stage?
I am bit confused, because it is listed the documentation here: https://metagraph.ethz.ch/static/docs/quick_start.html#annotate-with-pre-counting

**Comment by karasikov** [comment]
That's right. It used to be possible to do only via `clean`.
Recently we adapted `transform` for this as well and updated the docs.

However, the version on bioconda hasn't been updated yet. It will update with the next release.
So, if you're pulling metagraph from bioconda, it would explain the problem.

**Comment by MitraDarja** [comment]
Ah ok, thanks for the clearification!
