### ISSUE TITLE
"lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing" using metagraph build

### ISSUE THREAD

**Issue by matt-shenton** [ratschlab/metagraph#465]
Hi there,

I'm receiving this warning:
lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
Output information may be incomplete.

when building using
metagraph build  -v -p 8 --mem-cap-gb 40  --disk-swap ./temp 

as a normal user on this system I don't have access to /sys/kernel/debug/tracing
so I guess that's the reason. Can I safely ignore the warning?

Thanks in advance,
Best regards

Matt

**Comment by karasikov** [comment]
Hi Matt,

MetaGraph calls `lsof` to get the system's maximum number of open file descriptors.
The warning seems to be from this command.

However, as long as the process finishes fine, the result is correct.

So, you can ignore that message, yes.

**Comment by matt-shenton** [comment]
Many thanks!
