### ISSUE TITLE
Cannot install phyton API

### ISSUE THREAD

**Issue by carlaperezmon** [ratschlab/metagraph#471]
Hi! 

I am trying to install the metagraph API for phyton following the instructions in: https://metagraph.ethz.ch/static/docs/api.html

Concretely, I am trying the installation in my University's Research Compute Cluster. For that I first created a phyton environment, activated the environment and proceeded to the instructions in the link. 

I run the command

pip install -U "git+https://github.com/ratschlab/metagraph.git#subdirectory=metagraph/api/python"

But almost immediately I get the error: 
Collecting git+https://github.com/ratschlab/metagraph.git#subdirectory=metagraph/api/python
  Cloning https://github.com/ratschlab/metagraph.git to /tmp/pip-ji0s4i89-build
**fatal: reference is not a tree: 4dac46369afd3a0bd972563ad1d907bfb0c07bc8
Unable to checkout '4dac46369afd3a0bd972563ad1d907bfb0c07bc8' in submodule path 'metagraph/external-libraries/sdust'
  Complete output from command /usr/bin/git submodule update --init --recursive -q:

  ----------------------------------------
  Command "/usr/bin/git submodule update --init --recursive -q" failed with error code 1 in /tmp/pip-ji0s4i89-build**

I read online that this could be a problem of not updating references in the module in github: https://stackoverflow.com/questions/13425298/git-submodule-update-fatal-error-reference-is-not-a-tree#:~:text=The%20error%20means%20that%20specific%20commit%20%28its%20sha1%29,or%20reset%20the%20changes%20to%20the%20latest%20version.

Do you know if this could be the case or would you suggest a solution to it? 

I could install the program via bioconda, however, I am interested on query some sequences against MetaSubs. Is that possible to do through the conda api? 

Many thanks for the help. 

Cheers, 

Carla

**Comment by karasikov** [comment]
Hi Carla,

This seems like an issue with `sdust`. I've just updated it, could you try again? (the same commands)
