### ISSUE TITLE
metagraph installation failing

### ISSUE THREAD

**Issue by carlaperezmon** [ratschlab/metagraph#472]
**I am trying to install metagraph API to align some samples against MetaSubs subset following the tutorial in: https://github.com/ratschlab/metagraph_paper_resources/blob/master/notebooks/metasub.ipynb 

I run the pip install command I get this output:** 

(metagraph) carla@carla-ThinkBook-13s-G2-ITL:~/Desktop/metagraph$ pip install -U "git+https://github.com/ratschlab/metagraph.git#subdirectory=metagraph/api/python"
Collecting git+https://github.com/ratschlab/metagraph.git#subdirectory=metagraph/api/python
  Cloning https://github.com/ratschlab/metagraph.git to /tmp/pip-req-build-aigbg8zi
  Running command git clone --filter=blob:none --quiet https://github.com/ratschlab/metagraph.git /tmp/pip-req-build-aigbg8zi
  Resolved https://github.com/ratschlab/metagraph.git to commit 5c2a12bd26cba5c5f8a15e7b9aa765aeebfe3474
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.22 in ./metagraph/lib/python3.10/site-packages (from metagraph-api==0.3.6) (2.1.1)
Requirement already satisfied: requests in ./metagraph/lib/python3.10/site-packages (from metagraph-api==0.3.6) (2.31.0)
Requirement already satisfied: pytz>=2020.1 in ./metagraph/lib/python3.10/site-packages (from pandas>=0.22->metagraph-api==0.3.6) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./metagraph/lib/python3.10/site-packages (from pandas>=0.22->metagraph-api==0.3.6) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in ./metagraph/lib/python3.10/site-packages (from pandas>=0.22->metagraph-api==0.3.6) (2023.3)
Requirement already satisfied: numpy>=1.22.4 in ./metagraph/lib/python3.10/site-packages (from pandas>=0.22->metagraph-api==0.3.6) (1.26.0)
Requirement already satisfied: idna<4,>=2.5 in ./metagraph/lib/python3.10/site-packages (from requests->metagraph-api==0.3.6) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in ./metagraph/lib/python3.10/site-packages (from requests->metagraph-api==0.3.6) (2023.7.22)
Requirement already satisfied: charset-normalizer<4,>=2 in ./metagraph/lib/python3.10/site-packages (from requests->metagraph-api==0.3.6) (3.2.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./metagraph/lib/python3.10/site-packages (from requests->metagraph-api==0.3.6) (2.0.5)
Requirement already satisfied: six>=1.5 in ./metagraph/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=0.22->metagraph-api==0.3.6) (1.16.0)

**Nothing in the output confirms whether the API has installed or not. 

I nevertheless tried to run from python:**

from metagraph.client import GraphClient
metasub = GraphClient('dnaloc.ethz.ch', 80, api_path='/api/metasub19')
lbls = metasub.column_labels()

**but I get the error:** 

Traceback (most recent call last):
  File "/home/carla/Desktop/metagraph/metagraph/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Is the installation the problem?

**Comment by karasikov** [comment]
Hi there,

> Nothing in the output confirms whether the API has been installed or not.

It's a standard pip command. If it didn't print errors, the installation was successful.

Regarding the commands, currently MetaGraph Online hosts only MetaSUB with k=41, at the endpoint `/api/metasub41`.
(You can always see the list of currently hosted indexes and their endpoints at [https://metagraph.ethz.ch/graphs](https://metagraph.ethz.ch/graphs).)

```
from metagraph.client import GraphClient
metasub = GraphClient('metagraph.ethz.ch', 80, api_path='/api/metasub41')
metasub.search('AAAGTTGTGTAGTGCGATCGGTGGATGCCTTGGCACCAAGAGCCGATGAAGGACGTTGTGACCTGCGATAAGCCCTGGGGAGTTGGTGAGCGAGCTGTGATCCGGGGGTGTCCGAATGGG')
```

I quickly checked this index and, unfortunately, `.column_labels()` currently returns a wrong request error, but you can still do all the search commands as above.
(The problem with `.column_labels()` is due to the server not redirecting HTTP GET requests correctly, while PUT requests used for search work fine.)

If you host the indexes yourself locally or on your servers and connect the same way via API, you won't have this problem.
Let me know if you run into any issues or if you need the full list of columns for some index.

**Comment by carlaperezmon** [comment]
Many many thanks! The commands work fine now. I will try the labels later.
